[manifest]
version = "1.0.0"
priority = 0

# 0 Drivers of the chill vaction
# Changes planet card's softlock so that instead of requiring planets of have been played, they just need to be visible. Important for the House Rules Joker.
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''elseif v.enhancement_gate then'''
position = "before"
payload = '''if (not v.config.softlock or (v.key == "c_cbean_0chill_house_rules_planet" and next(SMODS.find_card('j_cbean_0chill_house_rules')) )) then
add = true
elseif (v.key == "c_cbean_0chill_house_rules_planet" and not next(SMODS.find_card('j_cbean_0chill_house_rules')) ) then
add = false
end
'''
match_indent = true
overide = true