[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#Change the reroll costs
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''local reroll_cost = G.GAME.current_round.reroll_cost'''
position = "before"
payload = '''
if not G.GAME.cbean_nteam_rerolls_left then
    G.GAME.cbean_nteam_rerolls_left = -1
end
if G.GAME.cbean_nteam_rerolls_left > 0 then
    G.GAME.cbean_nteam_rerolls_left = G.GAME.cbean_nteam_rerolls_left -1
elseif G.GAME.cbean_nteam_rerolls_left == 0 then
    G.GAME.round_resets.reroll_cost = G.GAME.round_resets.reroll_cost - G.GAME.cbean_nteam_rerolls_cost
    G.GAME.current_round.reroll_cost = G.GAME.current_round.reroll_cost - 3
    G.GAME.cbean_nteam_rerolls_left = G.GAME.cbean_nteam_rerolls_left -1
end
'''
match_indent = true

# Adds stickers to everything
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
    if _type == 'Joker' then
        if G.GAME.modifiers.all_eternal then
            card:set_eternal(true)
        end
'''
position = "before"
payload = '''
if G.GAME.modifiers.cbean_nteam_all_stickers then
    sendDebugMessage("Applying sticker to ".._type, "nteam_all_stickers")
    if _type == "Base" then
        _type = "Default"
    end
    if card.config.center.consumeable then
        _type = "Consumable"
    end
    local sticker_keys = {}
    for k, v in pairs(SMODS.Stickers) do
        if v.sets[_type] then 
            sticker_keys[#sticker_keys+1] = v.key
        end
    end
    if #sticker_keys > 0 then
        local sticker = pseudorandom(pseudoseed('cbean_nteam_all_stickers'), 1, #sticker_keys)
        sendDebugMessage("Found "..#sticker_keys.." applicable stickers, choosing "..sticker_keys[sticker],"nteam_all_stickers")
        card:add_sticker(sticker_keys[sticker], true)
    end
end
if G.GAME.modifiers.cbean_win_ante_poker then
    G.GAME.win_ante = 11
end
'''
match_indent = true

# Adds stickers to everything, deck cards edition
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
self.GAME.current_round.reroll_cost = self.GAME.base_reroll_cost
'''
position = "after"
payload = '''
if G.GAME.modifiers.cbean_nteam_all_stickers then
    sendDebugMessage("Applying stickers to deck", "nteam_all_stickers")
    local sticker_keys = {}
    for k, v in pairs(SMODS.Stickers) do
        if v.sets.Default then 
            if v.key ~= "rental" then
                sticker_keys[#sticker_keys+1] = v.key
            end
        end
    end
    if #sticker_keys > 0 then
        G.E_MANAGER:add_event(Event({
                func = function()
                    for k, v in pairs(G.playing_cards) do
                        local sticker = pseudorandom(pseudoseed('cbean_nteam_all_stickers'), 1, #sticker_keys)
                        sendDebugMessage("Found "..#sticker_keys.." applicable stickers, choosing "..sticker_keys[sticker],"nteam_all_stickers")
                        v:add_sticker(sticker_keys[sticker], true)
                    end
                return true
                end
            }))
    end
end
'''
match_indent = true

# modify pool
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''add = in_pool and (add or pool_opts.override_base_checks)'''
position = "after"
payload = '''
if G['P_BIOMES'][_type] and v.rarity ~= _rarity then
    add = false
end
'''
match_indent = true

# Add a "select_blind" context
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
for i = 1, #G.GAME.tags do
                    if G.GAME.tags[i]:apply_to_run({type = 'new_blind_choice'}) then break end
                end'''
position = "after"
payload = '''
SMODS.calculate_context({blind_select = true})
'''
match_indent = true

#Adds the House Rules tooltip to all House Rules jokers. Thank you hexacryonic for the code.
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "for _, v in ipairs(info_queue) do"
position = "before"
payload = '''for k, v in pairs(house_rules) do
  if _c.key == k then
    info_queue[#info_queue+1] = G.FUNCS.display_house_rules()
  end
end
'''
match_indent = true

#Adds the House Rules tooltip to all House Rules jokers. Thank you hexacryonic for the code.
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local info_queue = {}"
position = "after"
payload = '''local house_rules = {
            j_zany = {"sdown_flush_three"},
            j_wily = {"sdown_flush_three"},
            j_trio = {"sdown_flush_three"},
            j_jolly = {"sdown_flush_two"},
            j_sly = {"sdown_flush_two"},
            j_duo = {"sdown_flush_two"},
            j_8_ball = {"sdown_8r8k"},
            j_shortcut = {"sdown_pansexual","sdown_pansexual_flush"},
            j_obelisk = {"sdown_sacrifice"},
            j_sixth_sense = {"sdown_67", "sdown_flush_67"},
            j_cbean_colon_mu_cube = {"sdown_67", "sdown_flush_67"},
            j_marble = {"sdown_stone_hand"},
            j_stone = {"sdown_stone_hand"},
            j_cbean_0chill_driving_in_my_truck = {"0chill_deer_in_headlights"},
            j_cbean_colon_big_shot = {"0chill_favorite_year","0chill_favorite_year_flush"},
            j_fibonacci = {"0chill_fibonacci", "0chill_fibonacci_flush"},
            j_oops = {"0chill_jackpot"},
            j_cbean_0chill_nat20 = {"0chill_jackpot"},
            j_cbean_yma_set_of_dice = {"0chill_jackpot"},
            j_cbean_0chill_thorn_ring = {"0chill_proceed"},
            j_cbean_wgrop_withering_memory = {"wgrop_thorny_boquete"},
            j_seeing_double = {"sdown_true_home"},
            j_cbean_nameteam_diamondshapewithadotinside = {"sdown_true_home"},
            j_cbean_nameteam_sticker_collection = {"nteam_collection", "nteam_collection_3oak"},
            j_cbean_nameteam_stickerbomb = {"nteam_collection", "nteam_collection_3oak"}
}
'''
match_indent = true
