[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#Change the reroll costs
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''local reroll_cost = G.GAME.current_round.reroll_cost'''
position = "before"
payload = '''
if not G.GAME.cbean_nteam_rerolls_left then
    G.GAME.cbean_nteam_rerolls_left = -1
end
if G.GAME.cbean_nteam_rerolls_left > 0 then
    G.GAME.cbean_nteam_rerolls_left = G.GAME.cbean_nteam_rerolls_left -1
elseif G.GAME.cbean_nteam_rerolls_left == 0 then
    G.GAME.round_resets.reroll_cost = G.GAME.round_resets.reroll_cost - G.GAME.cbean_nteam_rerolls_cost
    G.GAME.current_round.reroll_cost = G.GAME.current_round.reroll_cost - 3
    G.GAME.cbean_nteam_rerolls_left = G.GAME.cbean_nteam_rerolls_left -1
end
'''
match_indent = true

# Adds stickers to everything
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
    if _type == 'Joker' then
        if G.GAME.modifiers.all_eternal then
            card:set_eternal(true)
        end
'''
position = "before"
payload = '''
if G.GAME.modifiers.cbean_nteam_all_stickers then
    sendDebugMessage("Applying sticker to ".._type, "nteam_all_stickers")
    if _type == "Base" then
        _type = "Default"
    end
    if card.config.center.consumeable then
        _type = "Consumable"
    end
    local sticker_keys = {}
    for k, v in pairs(SMODS.Stickers) do
        if v.sets[_type] then 
            sticker_keys[#sticker_keys+1] = v.key
        end
    end
    if #sticker_keys > 0 then
        local sticker = pseudorandom(pseudoseed('cbean_nteam_all_stickers'), 1, #sticker_keys)
        sendDebugMessage("Found "..#sticker_keys.." applicable stickers, choosing "..sticker_keys[sticker],"nteam_all_stickers")
        card:add_sticker(sticker_keys[sticker], true)
    end
end
if G.GAME.modifiers.cbean_win_ante_poker then
    G.GAME.win_ante = 11
end
'''
match_indent = true

# Adds stickers to everything, deck cards edition
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
self.GAME.current_round.reroll_cost = self.GAME.base_reroll_cost
'''
position = "after"
payload = '''
if G.GAME.modifiers.cbean_nteam_all_stickers then
    sendDebugMessage("Applying stickers to deck", "nteam_all_stickers")
    local sticker_keys = {}
    for k, v in pairs(SMODS.Stickers) do
        if v.sets.Default then 
            if v.key ~= "rental" then
                sticker_keys[#sticker_keys+1] = v.key
            end
        end
    end
    if #sticker_keys > 0 then
        G.E_MANAGER:add_event(Event({
                func = function()
                    for k, v in pairs(G.playing_cards) do
                        local sticker = pseudorandom(pseudoseed('cbean_nteam_all_stickers'), 1, #sticker_keys)
                        sendDebugMessage("Found "..#sticker_keys.." applicable stickers, choosing "..sticker_keys[sticker],"nteam_all_stickers")
                        v:add_sticker(sticker_keys[sticker], true)
                    end
                return true
                end
            }))
    end
end
'''
match_indent = true