
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "G.STATE = G.STATES.NEW_ROUND"
position = "at"
payload = '''
if NAMETEAM.no_progress and NAMETEAM.no_progress>0 and #G.deck.cards > 0 and not NAMETEAM.focre_progress then
    if G.GAME.current_round.hands_left == 1 then 
        NAMETEAM.no_progress = NAMETEAM.no_progress - 1  
        NAMETEAM.focre_progress = true
    end
    G.STATE = G.STATES.DRAW_TO_HAND
else
    if NAMETEAM.no_progress and NAMETEAM.no_progress>0 then
        NAMETEAM.msg((G.deck.cards[1] or G.deck), (NAMETEAM.no_progress .. " Rounds"))
    end
    NAMETEAM.focre_progress = false
    G.STATE = G.STATES.NEW_ROUND
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = " if G.GAME.facing_blind then G.GAME.current_round.any_hand_drawn = true end"
position = "before"
payload = '''
if not NAMETEAM.reduce then NAMETEAM.reduce = 0 end
if NAMETEAM.reduce>0 and not G.GAME.current_round.any_hand_drawn and G.GAME.blind.in_blind then
    NAMETEAM.reduce = NAMETEAM.reduce - 1
    if G.GAME.blind.boss then
        G.GAME.blind.chips = G.GAME.blind.chips/(G.P_CENTERS["j_cbean_doom_shroom"].config.extra.blind)
        G.GAME.blind.chip_text = number_format(G.GAME.blind.chips)
    else
        G.GAME.blind.chips = 0
        G.GAME.blind.chip_text = number_format(G.GAME.blind.chips)
    end
    NAMETEAM.msg(G.deck.cards[1], "Doom!")
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
    if card.ability.set ~= 'Joker' or #G.jokers.cards < G.jokers.config.card_limit + card_limit then'''
position = 'at'
payload = '''
    if (card.ability.set ~= 'Joker') or (#G.jokers.cards < G.jokers.config.card_limit + card_limit) or card.config.center.always_buyable then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
        for _, v in ipairs(SMODS.get_card_areas('playing_cards')) do
            SMODS.calculate_main_scoring({cardarea = v, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, v == G.play and scoring_hand or nil)
            delay(0.3)
        end'''
position = "at"
payload = '''
    if not (#SMODS.find_card("j_cbean_sap_fling")>0) then
        for _, v in ipairs(SMODS.get_card_areas('playing_cards')) do
            SMODS.calculate_main_scoring({cardarea = v, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, v == G.play and scoring_hand or nil)
            delay(0.3)
        end
    end
'''
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, final_scoring_step = true})'''
position = "after"
payload = '''
    if (#SMODS.find_card("j_cbean_sap_fling")>0) then
        for _, v in ipairs(SMODS.get_card_areas('playing_cards')) do
            SMODS.calculate_main_scoring({cardarea = v, full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands}, v == G.play and scoring_hand or nil)
            delay(0.3)
        end
    end
'''
match_indent = true
