[manifest]
version = "1.0.0"
dump_lua = true
priority = -1


# Sticker sets

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
key = "eternal",
'''
position = 'after'
payload = '''
sets = {
    Joker = true
},
'''
match_indent = false

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
key = "perishable",
'''
position = 'after'
payload = '''
sets = {
    Joker = true,
    Default = true,
    Enhanced = true,
},
'''
match_indent = false

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
key = "rental",
'''
position = 'after'
payload = '''
sets = {
    Joker = true,
    Default = true,
    Enhanced = true,
    Consumable = true,
},
'''
match_indent = false

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
key = "pinned",
'''
position = 'after'
payload = '''
sets = {
    Joker = true,
},
'''
match_indent = false

# Perishable trigger twice fix

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
            if context.end_of_round and not context.repetition and not context.individual then
                card:calculate_perishable()
            end
'''
position = 'at'
payload = '''
        if card.ability.set == "Default" or card.ability.set == "Enhanced" then
            if context.end_of_round and not card.cbean_temp_check then
                card.cbean_temp_check = true
                card:calculate_perishable()
            end
        elseif context.end_of_round and not context.repetition and not context.individual then
            card:calculate_perishable()
        end

'''
match_indent = false

# Rental trigger twice fix
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
            if context.end_of_round and not context.repetition and not context.individual then
                card:calculate_rental()
            end
'''
position = 'at'
payload = '''
        if card.ability.set == "Default" or card.ability.set == "Enhanced" then
            if context.end_of_round and not card.cbean_temp_check then
                card.cbean_temp_check = true
                card:calculate_rental()
            end
        elseif context.end_of_round and not context.repetition and not context.individual then
            card:calculate_rental()
        end

'''
match_indent = false


# Sticker Badges

# Add mod badge
# Apparently, this is taken from Papeback
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "badges.mod_set = nil"
position = "before"
payload = '''
for k, v in pairs(SMODS.Stickers) do
  if card and card.ability and string.find(k, "cbean") and card.ability[k] and G.your_collection then
    for i = 1, #G.your_collection do
        if card.area == G.your_collection[i] then
            SMODS.create_mod_badges(SMODS.Stickers[k], badges)
        end
    end
  end
end
'''
match_indent = true


# Adding sticker appearance in shops (this is so wrong istg)
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "create_shop_card_ui(card, v.type, area)"
position = "before"
payload = '''
for kk, vv in pairs(SMODS.ConsumableTypes) do
    if G.GAME.modifiers.consumable_stickers then
        if kk == v.type then
            local st = NAMETEAM.poll_sticker(false, card, true, "Consumable")
            if st then
                SMODS.Stickers[st]:apply(card, true)
            end
            break
        end
    end
end
'''
match_indent = true

# Sticker applied / removed

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
                        if k == 'card_limit' or k == 'extra_slots_used' then
                            card.ability[k] = (card.ability[k] or 0) + v
                        end
                    end
                end
            end
        end
'''
position = 'after'
payload = '''
,
NAMETEAM_applied = function(self, card) end,
NAMETEAM_removed = function(self, card) end,
'''
match_indent = false

# Dissolve checks
# this probably should be on something like card:remove but idc
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
if not no_juice then self:juice_up() end
'''
position = 'after'
payload = '''
if self.ability then
    for k, v in pairs(SMODS.Stickers) do
        if self.ability[k] and not SMODS.Stickers[k].no_dissolve_trigger then
            self:NAMETEAM_remove_sticker_calc(v, self)
        end
    end
 end
'''
match_indent = false

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
-- TARGET: add your own individual scoring targets
'''
position = "after"
payload = '''
if G.GAME.selected_back.ability then
    for k, v in pairs(G.GAME.selected_back.ability) do
        if v and SMODS.Stickers[k] then
            t[#t + 1] = { object = SMODS.Stickers[k], scored_card = G.deck.cards[1] or G.deck, tname_deck_sticker_calc = true }
        end
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
local eff, triggered = individual.object:calculate(context)
'''
position = "at"
payload = '''
local eff, triggered
if individual.tname_deck_sticker_calc then
    if individual.object.calculate then
        eff, triggered = individual.object:calculate(G.deck.cards[1] or G.deck, context)
    end
else
    eff, triggered = individual.object:calculate(context)
end
'''
match_indent = true

# Deck Stickers 

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
    G.CONTROLLER.locks.toggle_shop = true
    if G.shop then 
'''
position = "after"
payload = '''
if G.GAME.selected_back then
	if (pseudorandom("deck_sticker") < 1 / 4) and G.GAME.modifiers.deck_stickers then
		local ae = NAMETEAM.poll_sticker(true, G.GAME.selected_back, true, "Deck")
		if ae then
			G.GAME.selected_back:nteam_apply_sticker(ae)
            if G.deck.cards[1] then
                SMODS.calculate_effect { card = G.deck.cards[1] or G.deck, message = localize(ae, "labels") .. "!" }
            end
		end
	end
end
'''
match_indent = true

# The Serpent sticker

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
    if G.GAME.blind.name == 'The Serpent' and
        not G.GAME.blind.disabled and
        (G.GAME.current_round.hands_played > 0 or
        G.GAME.current_round.discards_used > 0) then
            hand_space = math.min(#G.deck.cards, 3)
    end
'''
position = "at"
payload = '''
    if (G.GAME.blind.name == 'The Serpent' and
        not G.GAME.blind.disabled or G.GAME.NAMETEAM_Serpent_Sticker) and
        (G.GAME.current_round.hands_played > 0 or
        G.GAME.current_round.discards_used > 0) then
            hand_space = math.min(#G.deck.cards, 3)
    end
'''
match_indent = true

# Deck Blind Sticker apply function

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
SMODS.calculate_context({end_of_round = true, game_over = game_over, beat_boss = G.GAME.blind.boss })
'''
position = "after"
payload = '''
if G.GAME.round_resets.ante > 7 and G.GAME.modifiers.blind_stickers and not G.GAME.modifiers.showdown_stickers then
    G.GAME.modifiers.showdown_stickers = true
end
if G.GAME.modifiers.blind_stickers and G.GAME.blind.boss then
        local tab = {}
        local ae = NAMETEAM.poll_sticker(true, G.GAME.selected_back, true, "Blind")
          
        for k, v in pairs(SMODS.Stickers) do
            if v.sets and v.sets["Blind"] then
                if v.showdown_sticker then
                    if G.GAME.modifiers.showdown_stickers then
                        tab[#tab+1] = k
                    end
                else
                    tab[#tab+1] = k
                end
            end
        end

        for k, v in pairs(tab) do
            if G.GAME.selected_back.ability[v] then
                G.GAME.selected_back:nteam_remove_sticker(v)
            end
        end

        G.GAME.selected_back:nteam_apply_sticker(ae)
    end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
    if self.facing == 'front' and (not self.states.drag.is or G.CONTROLLER.HID.touch) and not self.no_ui and not G.debug_tooltip_toggle then 
'''
position = "at"
payload = '''
    if (self.facing == 'front' or (G.deck and self == G.deck.cards[1])) and (not self.states.drag.is or G.CONTROLLER.HID.touch) and not self.no_ui and not G.debug_tooltip_toggle then 
'''
match_indent = true
