[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = 'engine/text.lua'
pattern = '''
    self.font = config.font or G.LANG.font
'''
position = "at"
payload = '''
self.font = SMODS.Fonts["cbean_ewfontassetthing"] -- this better bloody work
'''
match_indent = true

# PINK MAINMENU
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
            {name = 'colour_1', ref_table = G.C, ref_value = 'RED'},
            {name = 'colour_2', ref_table = G.C, ref_value = 'BLUE'},
'''
position = "at"
payload = '''
            {name = 'colour_1', ref_table = G.C, ref_value = 'VOUCHER'},
            {name = 'colour_2', ref_table = G.C, ref_value = 'VOUCHER'},
'''
match_indent = true

#PINK INTRO
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
                    {name = 'colour_1', ref_table = G.C, ref_value = 'BLUE'},
                    {name = 'colour_2', ref_table = G.C, ref_value = 'WHITE'},
'''
position = "at"
payload = ''' 
                    {name = 'colour_1', ref_table = G.C, ref_value = 'VOUCHER'},
                    {name = 'colour_2', ref_table = G.C, ref_value = 'VOUCHER'},
'''
match_indent = true