[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# wgrop
# biome select instead of shop
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.STATE = G.STATES.SHOP'''
position = "at"
payload = '''
-- Show the biome select screen if after CEO blind
if G.WGRP_CEOBLIND then
G.STATE = G.STATES.BIOMETREE
G.WGRP_CEOBLIND = false
else
G.STATE = G.STATES.SHOP
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''if  G.GAME and G.GAME.blind and G.GAME.blind.get_type then'''
position = "after"
payload = '''
if (G.GAME.blind:get_type() == 'CEO') then
    G.WGRP_CEOBLIND = true
else
    G.WGRP_CEOBLIND = false
end
'''
match_indent = true

# biome select
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''if self.STATE == self.STATES.PLAY_TAROT then '''
position = "before"
payload = '''
if self.STATE == self.STATES.BIOMETREE then
    update_wgrop_biometree()
end
'''
match_indent = true