[manifest]
version = "1.0.0"
dump_lua = true
priority = 99


# Changes it so that you have to beat the CEO Blind to win
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if not G.GAME.won and G.GAME.round_resets.ante >= G.GAME.win_ante and G.GAME.blind:get_type() == 'Boss' then"
position = "at"
payload = "if not G.GAME.won and G.GAME.round_resets.ante >= G.GAME.win_ante and G.GAME.blind_on_deck == 'CEO' then"
match_indent = true