[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Yeah Mostly Artists

# Random pool
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''local _pool, _starting_pool, _pool_key, _pool_size = G.ARGS.TEMP_POOL, nil, '', 0'''
position = "after"
match_indent = true
payload = '''
if next(SMODS.find_card("c_cbean_yma_enigma")) then
    for k, v in pairs(SMODS.ConsumableTypes) do
        if _type == k then
            local _pool, discard_key2 = get_current_pool('Consumeables')
        end
    end
end
'''

# Pool fix for Seeing Stars
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif _type == 'Joker' then _pool[#_pool + 1] = "j_joker"'''
position = "before"
match_indent = true
payload = '''
elseif _type == 'Joker' and next(SMODS.find_card("j_cbean_yma_seeing_stars")) then _pool[#_pool + 1] = "j_astronomer"
'''

# Before before context
[[patches]] 
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)
'''
position = "before"
payload = '''
local fake_text,fake_disp_text,fake_poker_hands,fake_scoring_hand,fake_non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = fake_scoring_hand, scoring_name = fake_text, poker_hands = fake_poker_hands, yma_before_before = true})
'''
match_indent = true

# Stops redeeming a voucher from crashing
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = 'before'
pattern = '''G.CONTROLLER:snap_to({node = G.shop:get_UIE_by_ID('next_round_button')})'''
payload = '''
if G.shop then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = 'after'
pattern = '''G.CONTROLLER:snap_to({node = G.shop:get_UIE_by_ID('next_round_button')})'''
payload = '''
end
'''
match_indent = true


# Resets temporary consumeable cards
[[patches]] 
[patches.pattern]
target = "functions/common_events.lua"
pattern = "-- TARGET: evaluate your own general effects"
position = "before"
match_indent = true
payload = '''
if context.cardarea == G.consumeables then
    for k, v in pairs(G.consumeables.cards) do
        if v.ability and v.ability.yma_temp_key and context[v.ability.yma_context] then
            local key = v.ability.yma_temp_key
            v.ability.yma_temp_key = nil
            G.E_MANAGER:add_event(Event({
                trigger = 'before',
                delay = 0.0,
                func = (function()
                    card_eval_status_text(card, "extra", nil, nil, nil, {message = localize("k_reset"), colour = G.C.FILTER})
                    YMA_reroll_card(v, key, v.ability.yma_temp_set, nil, nil, v.ability.yma_temp_ability_table, true)
                    return true
                end)
            }))
        end
        if v.ability and v.ability.yma_failed_pray then
            v.ability.yma_failed_pray = nil
        end
    end
end
if context.cardarea == G.jokers then
    for k, v in pairs(G.jokers.cards) do
        if v.ability and v.ability.yma_quest_temporary and context[v.ability.yma_context] then
            v.ability.yma_quest_temporary = nil
            SMODS.destroy_cards(v, nil, nil, true)
            SMODS.calculate_effect({message = localize('k_yma_key_faded') }, v)
        end
    end
end
if context.ending_shop and G.GAME.cbean.patience_quest then
    G.GAME.cbean.patience_quest = false
    SMODS.change_free_rerolls(-5)
end
'''
# if context.starting_shop and G.GAME.cbean.patience_quest then
#     SMODS.change_free_rerolls(5)
# end
# if context.ending_shop and G.GAME.cbean.patience_quest then
#     G.GAME.cbean.patience_quest = false
#     SMODS.change_free_rerolls(-5)
# end

# Before After context
[[patches]] 
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
G.E_MANAGER:add_event(Event({
    trigger = 'after',delay = 0.4,
    func = (function()  update_hand_text({delay = 0, immediate = true}, {mult = 0, chips = 0, chip_total = math.floor( SMODS.calculate_round_score() ), level = '', handname = ''});play_sound('button', 0.9, 0.6);return true end)
}))
'''
position = "before"
payload = '''
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, yma = {before_after = true}, total_chips = math.floor(SMODS.calculate_round_score())})
'''
match_indent = true

# Game:update
[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'before'
pattern = '''if self.STATE == self.STATES.PLAY_TAROT then'''
payload = '''
if self.STATE == self.STATES.GRAVEYARD then
  update_graveyard()
end
if self.STATE == self.STATES.MAIN_STREET then
  update_main_street()
end
if self.STATE == self.STATES.HELL then
  update_yma_hell()
end
if self.STATE == self.STATES.DREAMLAND then
  update_yma_dreamland()
end
'''
match_indent = true

# ease_background_colour_blind
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
position = 'before'
pattern = '''elseif state == G.STATES.TAROT_PACK then'''
payload = '''
elseif state == G.STATES.GRAVEYARD then
    ease_colour(G.C.DYN_UI.MAIN, mix_colours(G.C.GREY, G.C.BLACK, 0.9))
'''
match_indent = true

# TEMPORARY PATCH (probably not temporary)
# save_run
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
position = 'at'
pattern = '''STATE = G.STATE,'''
payload = '''
STATE = G.STATE == G.STATES.GRAVEYARD and G.STATES.SHOP or G.STATE,
STATE = G.STATE == G.STATES.HELL and G.STATES.SHOP or G.STATE,
STATE = G.STATE == G.STATES.MAIN_STREET and G.STATES.SHOP or G.STATE,
STATE = G.STATE == G.STATES.DREAMLAND and G.STATES.SHOP or G.STATE,
'''
match_indent = true

# Remove areas when closing the run and what not
[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'after'
pattern = '''if self.shop then self.shop:remove(); self.shop = nil end'''
payload = '''
if self.graveyard then self.graveyard:remove(); self.graveyard = nil end
if self.yma_hell then self.yma_hell:remove(); self.yma_hell = nil end
if self.main_street then self.main_street:remove(); self.main_street = nil end
if self.yma_dreamland then self.yma_dreamland:remove(); self.yma_dreamland = nil end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = 'after'
pattern = '''G.shop = nil'''
payload = '''
if G.graveyard then
  G.graveyard:remove()
  G.graveyard = nil
end
if G.main_street then
  G.main_street:remove()
  G.main_street = nil
end
if G.yma_hell then
  G.yma_hell:remove()
  G.yma_hell = nil
end
if G.yma_dreamland then
  G.yma_dreamland:remove()
  G.yma_dreamland = nil
end
'''
match_indent = true

# Game Variables
[[patches]] #G.GAME 
[patches.pattern]
target = 'game.lua'
pattern = '''
unused_discards = 0,'''
position = 'after'
payload = '''
cbean = {
    quest_complete = false,
    completed_quests = {},
    destroyed_jokers = {},
    patience_quest = false,
},
'''
match_indent = true 

# [Side Quests] Makes cardarea work with calculate function
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''-- TARGET: add your own CardAreas for joker evaluation'''
position = "before"
payload = '''
    if G.side_quests then
        table.insert(t, G.side_quests)
    end
    if G.dreamlands_consumeable_card_holder then
        table.insert(t, 1, G.dreamlands_consumeable_card_holder)
    end
'''
match_indent = true

# Fixes problem of area not existing
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.play = CardArea("
position = "before"
match_indent = true
payload = '''
self.dreamlands_consumeable_card_holder = CardArea(
      self.hand.T.x+0,
      self.hand.T.y+G.ROOM.T.y + 9,
      math.min(10*1.02*self.CARD_W,4.08*self.CARD_W),
      1.05*self.CARD_H, 
      {card_limit = 999999999999, type = 'consumeable', highlight_limit = 1})
'''

# [Side Quests] - Create a new quest upon completion
[[patches]] #G.GAME 
[patches.pattern]
target = 'game.lua'
pattern = '''function Game:update(dt)'''
position = 'after'
payload = '''
    if G.GAME.cbean_quest_complete then
        SMODS.add_card { set = "yma_quest", area = G.side_quests }
        G.GAME.cbean_quest_complete = false
    end
'''
match_indent = true 

# [Side Quests] - Default Pool
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''elseif _type == 'Joker' then _pool[#_pool + 1] = "j_joker"'''
position = 'before'
payload = '''
elseif _type == 'yma_quest' then _pool[#_pool + 1] = "q_cbean_yma_credit_card"
'''
match_indent = true
