[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Yeah Mostly Artists
# Random pool
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''local _pool, _starting_pool, _pool_key, _pool_size = G.ARGS.TEMP_POOL, nil, '', 0'''
position = "after"
match_indent = true
payload = '''
if next(SMODS.find_card("c_cbean_yma_enigma")) then
    for k, v in pairs(SMODS.ConsumableTypes) do
        if _type == k then
            local _pool, discard_key2 = get_current_pool('Consumeables')
        end
    end
end
'''

# Game Variables
[[patches]] #G.GAME 
[patches.pattern]
target = 'game.lua'
pattern = '''
unused_discards = 0,'''
position = 'after'
match_indent = true 
payload = '''
cbean = {
    quest_complete = false,
},

'''

# [Side Quests] Makes cardarea work with calculate function
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''        -- TARGET: add your own CardAreas for joker evaluation'''
position = "before"
payload = '''
    if G.side_quests then
        table.insert(t, G.side_quests)
    end
    '''
match_indent = true

# [Side Quests] - Create a new quest upon completion
[[patches]] #G.GAME 
[patches.pattern]
target = 'game.lua'
pattern = '''function Game:update(dt)'''
position = 'after'
match_indent = true 
payload = '''
    if G.GAME.cbean_quest_complete then
        SMODS.add_card { set = "yma_quest", area = G.side_quests }
        G.GAME.cbean_quest_complete = false
    end
'''
